services:
  web-oven-ap-lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-oven-ap-lab
    restart: unless-stopped
    ports:
      - "3006:3000"
    environment:
      - DATABASE_URL=postgresql://ap_user:${POSTGRES_PASSWORD}@ap_lab_db:5432/ap_lab_db
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://ap-lab.g-labs.my.id}
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@g-labs.my.id}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - ADMIN_NAME=${ADMIN_NAME:-Gerald Arya Dewangga}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_EMAIL_FROM=${RESEND_EMAIL_FROM:-noreply@g-labs.my.id}
      - TZ=Asia/Jakarta
      - PGTZ=Asia/Jakarta
    depends_on:
      ap_lab_db:
        condition: service_healthy
    networks:
      - ap_lab_net

  ap_lab_db:
    image: postgres:15-alpine
    container_name: ap_lab_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5436:5432"
    environment:
      POSTGRES_DB: ap_lab_db
      POSTGRES_USER: ap_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    volumes:
      - ap_lab_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ap_user -d ap_lab_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ap_lab_net

volumes:
  ap_lab_pgdata:

networks:
  ap_lab_net:
    driver: bridge
